---
title: "Forest Plot Compare Groups"
author: "Arnau Lagarda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(compareGroups)
library(ggplot2)
library(ggpubr)
library(Hmisc)
```

# Simulating Data 

First, we'll simulate a dataset with a binary outcome, and a mix of categorical and numerical continuous variables.

```{r}
# Set seed for reproducibility
set.seed(123)

# Simulate data
n <- 500
data <- data.frame(
  outcome = rbinom(n, 1, 0.5),
  cat_var1 = factor(sample(letters[1:3], n, replace = TRUE)),
  cat_var2 = factor(sample(letters[4:6], n, replace = TRUE)),
  cont_var1 = abs(rnorm(n)),
  cont_var2 = abs(runif(n))
)

# Show first few rows of the dataset
head(data)
```

# compareGroups analysis 

We will use the `compareGroups` package to perform the analysis, including calculating the odds ratios.

```{r}
# Perform compareGroups analysis
result <- compareGroups(outcome ~ ., data = data, method = c(2, 3),compute.ratio = T,)

# Create a summary table
summary(result)

```

# Forest Plot of Odds Ratios

```{r}
# Extract odds ratio data for plotting
tbl<-getResults(result,what="ratio")
or_data <- as.data.frame(tbl)
or_data <- tibble::rownames_to_column(or_data)


# Rename columns for clarity
colnames(or_data) <- c("Variable","OR", "Lower", "Upper", "p")

# Remove NAs and infinite values
or_data <- or_data %>%
  filter(!is.na(OR) & is.finite(OR))

or_data <- or_data %>%
  mutate(label = paste0(sprintf("%.2f", OR), " [", sprintf("%.2f", Lower), ":", sprintf("%.2f", Upper), "]"))

or_data<- or_data %>% dplyr::mutate(signif=if_else(Lower > 1 | Upper < 1,1,0))
# Create the forest plot
forest_plot <- ggplot(or_data, aes(x = Variable, y = OR, ymin = Lower, ymax = Upper,col=as.factor(signif))) + scale_y_log10()+
  geom_pointrange() +
  geom_hline(yintercept = 1, linetype = "dashed") +
  coord_flip() +
  xlab("Variable") +
  ylab("Odds Ratio [95% CI]") +
  ggtitle("Forest Plot of Odds Ratios")+geom_vline(xintercept=0, color='black', linetype='dashed', alpha=.5) +
  geom_text(aes(label = label), hjust = -0.2, vjust = -0.5)+
  theme_minimal()+theme(legend.position="none")

# Print the plot
forest_plot

```

